version: '3.8'
services:
  flaskapp:
    build:
      context: .
      dockerfile: flaskapp.dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - minio
      - postgres
      - redis
    environment:
      FLASK_ENV: development

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  minio_data:
  postgres_data:
  redis_data:
